# Generated by Django 5.0.1 on 2024-01-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('employee_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('middleName', models.CharField(max_length=255)),
                ('surName', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=255)),
                ('jobTitle', models.CharField(max_length=255)),
                ('officeLocation', models.CharField(max_length=255)),
                ('managerEmployeeID', models.IntegerField()),
                ('isEnabled', models.BooleanField()),
                ('isAssetOwner', models.BooleanField()),
                ('lastLoginAD', models.DateTimeField()),
                ('lastLoginAPP', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='UserStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
                ('userType', models.CharField(max_length=255)),
            ],
        ),
    ]
