# Generated by Django 5.0.1 on 2024-01-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='jobTitle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastLoginAD',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastLoginAPP',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='middleName',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='users',
            name='officeLocation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
