# Generated by Django 5.0.1 on 2024-01-19 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0002_users_userstatus_users_usertype'),
    ]

    operations = [
        migrations.AddField(
            model_name='systems',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
