# Generated by Django 5.0.1 on 2024-01-13 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0002_alter_users_jobtitle_alter_users_lastloginad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='lastLoginAD',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 13, 22, 12, 41, 524003)),
        ),
        migrations.AlterField(
            model_name='users',
            name='lastLoginAPP',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 1, 13, 22, 12, 41, 524003)),
        ),
        migrations.AlterField(
            model_name='users',
            name='middleName',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
