# Generated by Django 5.0.1 on 2024-01-13 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0003_alter_users_lastloginad_alter_users_lastloginapp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='isAssetOwner',
        ),
        migrations.RemoveField(
            model_name='users',
            name='isEnabled',
        ),
        migrations.RemoveField(
            model_name='users',
            name='jobTitle',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastLoginAD',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lastLoginAPP',
        ),
        migrations.RemoveField(
            model_name='users',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='users',
            name='managerEmployeeID',
        ),
        migrations.RemoveField(
            model_name='users',
            name='middleName',
        ),
        migrations.RemoveField(
            model_name='users',
            name='officeLocation',
        ),
        migrations.RemoveField(
            model_name='users',
            name='surName',
        ),
    ]
