# Generated by Django 5.0.1 on 2024-01-13 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0004_remove_users_isassetowner_remove_users_isenabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='managerEmployeeID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ARapp.users'),
            preserve_default=False,
        ),
    ]
