# Generated by Django 5.0.1 on 2024-01-19 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0004_country_r_reviewlist_r_reviewresponseoptions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='country',
        ),
    ]
