# Generated by Django 5.0.1 on 2024-01-19 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0005_remove_country_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_reviewlist',
            name='additionalActionsDone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='additionalActionsDoneTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='allManagersDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='allManagersDoneTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='allUsersDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='allUsersDoneTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='assetOwnerDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='assetOwnerDoneTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='reviewDone',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='reviewDoneTime',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='reviewEnd',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='reviewRanBy',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='r_reviewlist',
            name='reviewStart',
            field=models.DateTimeField(null=True),
        ),
    ]
