# Generated by Django 5.0.1 on 2024-01-19 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0006_r_reviewlist_additionalactionsdone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='userStatus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ARapp.userstatus'),
        ),
        migrations.AlterField(
            model_name='users',
            name='userType',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='ARapp.usertype'),
        ),
    ]
