# Generated by Django 5.0.1 on 2024-01-14 08:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0006_systems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='managerEmployeeID',
        ),
        migrations.AddField(
            model_name='users',
            name='userStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ARapp.userstatus'),
            preserve_default=False,
        ),
    ]
