# Generated by Django 5.0.1 on 2024-01-14 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0007_remove_users_manageremployeeid_users_userstatus'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userType', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='userstatus',
            name='userType',
        ),
        migrations.AddField(
            model_name='users',
            name='userType',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='ARapp.usertype'),
            preserve_default=False,
        ),
    ]
