# Generated by Django 4.2.9 on 2024-01-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0007_alter_users_userstatus_alter_users_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systems',
            name='country',
        ),
        migrations.AddField(
            model_name='systems',
            name='country',
            field=models.ManyToManyField(to='ARapp.country'),
        ),
    ]
