# Generated by Django 5.0.1 on 2024-01-14 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0008_usertype_remove_userstatus_usertype_users_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userType',
        ),
    ]
