# Generated by Django 4.2.9 on 2024-01-19 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0008_remove_systems_country_systems_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systems',
            name='country',
        ),
        migrations.AddField(
            model_name='country',
            name='system',
            field=models.ManyToManyField(to='ARapp.systems'),
        ),
    ]
