# Generated by Django 5.0.1 on 2024-01-14 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0009_remove_users_usertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='userStatus',
        ),
    ]
