# Generated by Django 4.2.9 on 2024-01-19 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0009_remove_systems_country_country_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='system',
        ),
        migrations.AddField(
            model_name='systems',
            name='country',
            field=models.ManyToManyField(to='ARapp.country'),
        ),
    ]
