# Generated by Django 4.2.9 on 2024-01-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0010_remove_country_system_systems_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='systems',
            name='systemDescription',
            field=models.TextField(null=True),
        ),
    ]
