# Generated by Django 4.2.9 on 2024-01-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0011_systems_systemdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='r_reviewlist',
            name='country',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
