# Generated by Django 4.2.9 on 2024-01-20 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0012_r_reviewlist_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_reviewlist',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ARapp.systems'),
        ),
    ]
