# Generated by Django 4.2.9 on 2024-01-20 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ARapp', '0013_alter_r_reviewlist_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='r_reviewlist',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ARapp.country'),
        ),
    ]
